---
- name: Hello World!
  remote_user: root
  hosts: all
  tasks:
  - name: Hello World!
    shell: echo "Hi! AWX is working."
  - name: install base packages
    yum: name={{ item }}  state=installed
    with_items:
      - python-pip
      - git
