---
- name: Hello World!
  hosts: all
 
  tasks:
 
  - name: Hello World!
    shell: echo "Hi! Tower is working."
  - copy: src=/root/log1/login dest=/root/test/test.conf owner=root group=root mode=644
