---
- name: Hello World!
  remote_user: root
  hosts: all
  tasks:
  - name: Hello World!
    shell: echo "Hi! AWX is working."
    tags:
       - message_display
  - name: install base packages
    tags:
       - package installation
    yum: name={{ item }} state=installed
    with_items:
      - git
